### ISSUE TITLE
Testing on docker swarm

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/docker-strabon#1]
Please provide docker-compose v2 definition compatible with docker swarm and instructions on how to run it inside swarm

**Comment by gioargyr** [comment]
There is already a docker-compose snippet in the current repo.

**Comment by earthquakesan** [comment]
Named volumes with a volume driver should be used in the snippet, refer to [this issue](https://docs.docker.com/compose/swarm/#/host-ports-and-recreating-containers).
