### ISSUE TITLE
Tomcat security issue due to created admin user

### ISSUE THREAD

**Issue by gmouchakis** [big-data-europe/docker-strabon#2]
Along with Tomcat an admin user is created. I do not see any usage for an admin user in Strabon's case and such a user can cause serious security issues. Also the username and password are always the same.

If there is no need for a Tomcat admin user it should be removed or at least make the username and password random.

**Comment by gioargyr** [comment]
Yiannis, I think you are right! I merged your pull request
Thanks for the commit.
